CREATE TABLE MOVIE_GENRE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    movieId INT,
    genreId INT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (movieId) REFERENCES MOVIE(id),
    FOREIGN KEY (genreId) REFERENCES GENRE(id)
);