CREATE TABLE MOVIE_CHARACTER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    movieId INT,
    characterId INT,
    actorId INT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (movieId) REFERENCES MOVIE(id),
    FOREIGN KEY (characterId) REFERENCES CHARACTER_TABLE(id),
    FOREIGN KEY (actorId) REFERENCES PERSON(id)
);