CREATE TABLE USER_FAVORITE_MOVIE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT,
    movieId INT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES USER(id),
    FOREIGN KEY (movieId) REFERENCES MOVIE(id)
);